# -*- coding: utf-8 -*-
"""IPL_Score_Predictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14YFdmIlJXj2vbxk-KvfVYz0atqbhxXts
"""

!pip install lazypredict
import lazypredict
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset= pd.read_csv('ipl.csv', parse_dates= ['date'])

dataset.info()

dataset.isnull().sum()

dataset.head()

dataset.drop(columns= ['mid', 'date', 'venue', 'batsman', 'bowler', 'striker', 'non-striker'], axis=1, inplace= True)

dataset.head()

dataset['bat_team'].unique()

dataset['bowl_team'].unique()

consistent_teams = ['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
                    'Mumbai Indians', 'Kings XI Punjab', 'Royal Challengers Bangalore',
                    'Delhi Daredevils', 'Sunrisers Hyderabad']

dataset= dataset[(dataset['bat_team'].isin(consistent_teams)) & (dataset['bowl_team'].isin(consistent_teams))]

dataset['bat_team'].unique()

dataset['bowl_team'].unique()

dataset = dataset[dataset['overs']>=5.0]

dataset.head()

x= dataset.iloc[:, :-1]
y= dataset.iloc[:, -1]

print(x)

x= pd.get_dummies(data=x, columns=['bat_team', 'bowl_team'])

x.head()

y.head()

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

print(x_train)

print(x_test)

print(y_train)

print(y_test)

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 850, random_state = 0)
regressor.fit(x_train, y_train)

y_pred = regressor.predict(x_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

import pickle
filename = 'first-innings-score-lr-model.pkl'
pickle.dump(regressor, open(filename, 'wb'))